[project]
name = "image-extraction-knn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.6"
dependencies = [
    "jupyter>=1.1.1",
    "scikit-image~=0.25.2",
]
